### PR TITLE
Add bors

### PR DESCRIPTION
**Pull request by mythmon**
Part of #170.

### CODE REVIEW

**Comment by mythmon** [comment]
This is marked as `bors-dont-merge` for two reasons. First, it will let us test the feature, and second, this is not ready to merge because bors is not set up on the repo yet, pending [Bug 1479830](https://bugzilla.mozilla.org/show_bug.cgi?id=1479830).

**Comment by mythmon** [comment]
Bors is supposed to be set up now.

bors ping

**Comment by mythmon** [comment]
@peterbe when you're happy with this, go ahead and say "bors r+", which can be in the approval message. It should fail due to the `bors-dont-merge` tag. Then we'll remove that tag and do it for real.

**Comment by mythmon** [comment]
bors r= peterbe

**Comment by mythmon** [comment]
The first r+ failed because I got the type of `block_labels` configuration wrong. I fixed that, and now bors did the right hting.

**Comment by mythmon** [comment]
@peterbe ok, the last step is to change your "Request changes" review to an approval, and say `bors r+` one more time.

**Comment by peterbe** [comment]
Cancelled?? By who?

**Comment by mythmon** [comment]
I've never seen bors do that before. That's strange. Do you have the circleci config to automatically cancel redundant builds? Maybe that was it.

bors retry

**Comment by mythmon** [comment]
I checked a bit more, and "canceled" here means that bors failed to merge the PR, but not that the PR is bad. It turns out that this repo only allowed certain users to push to the master branch, and so bors was getting denied. I fixed that, and now bors should work fine.

bors retry

**Comment by peterbe** [comment]
> I fixed that, and now bors should work fine.

What did you fix?

**Comment by mythmon** [comment]
> What did you fix?

I removed the restriction of *who* could push to master, and added the restriction that the `bors` status check must pass on the commit.

**Comment by mythmon** [comment]
bors r= @peterbe

**Pull request merged**
